all: xmldoc.pdf userman.pdf

xmldoc.pdf: xmldoc.tex
	latex -output-format=pdf xmldoc.tex;\
	latex -output-format=pdf xmldoc.tex

userman.pdf: userman.tex
	latex -output-format=pdf userman.tex;\
	latex -output-format=pdf userman.tex

