.TH tracedns 1 LOCAL

.SH NAME

tracedns - the libtrace based frontend for dns2sqlite (part of DNS2db) 

.SH SYNOPSIS
.B tracedns 
 [ \-\-filter | \-f bpfexp ] [ \-\-snaplen | \-s snap ] 
 [ \-\-promisc | \-p flag] [ \-\-help | \-h ] 
 [ \-\-libtrace\-help | \-H ] libtraceuri...

.SH AVAILABILITY
Linux / BSD 
.SH DESCRIPTION
tracedns is a networksniffer that uses the libtrace library to prepare packets for dns2sqlite.
.SH OPTIONS
.TP 5

--filter | -f
specifies a bpf filter to run on all incoming packet usually something like "port 53"

.TP
--snaplen | -s 
specifies the snaplength. Cuts all packets at snaplength ignoring any bytes after the specified lenght. 

.TP
--promisc | -p flag
set the interface in promisc mode

.TP
--help | -h
prints usage help

.TP
--libtrace-help | -H
provides help about available libtraceuri's

.TP
libtraceuri
see "tracedns -H" for the available libtraceuri's. 
Examples are "pcapint:eth0" or "pcapfile:/foo/bar.pcap" 

.SH EXAMPLES
.TP
Listens on interface eth0 for any packets on port 53 and outputs the data to stdout.

tracedns -f "port 53" pcapint:eth0 

.SH AUTHOR
\ .SE (The Internet Infrastructure Foundation) - opensource.iis.se
